drop table if exists board CASCADE;

create table board
(
    id       bigint generated by default as identity,
    title    varchar(255),
    password varchar(255),
    content  varchar(1000),
    primary key (id)
);