drop table if exists board CASCADE;

create table board
(
    id       bigint generated by default as identity,
    name     varchar(255),
    title    varchar(255),
    password varchar(255),
    content  varchar(1000),
    date     DATETIME not null default CURRENT_TIMESTAMP,
    primary key (id)
);